### ISSUE TITLE
move bfe.json to spec repo

### ISSUE THREAD

**Issue by mixmix** [ssb-ngi-pointer/ssb-bfe#15]
I would like `bfe.json` to be in the spec repo

reasons:
- version lock the spec description with the programmatic definitions
- less js for repos which are in other languages

**Comment by arj03** [comment]
Fine by me, just as long as we keep bfeTypes & bfeNamedTypes "links" in this library. Makes it easier to use I think.

**Comment by mixmix** [comment]
Agree. I want only the minimum data in the spec. Purple can do what they want with it after that.
