### ISSUE TITLE
encode(buf) => buf

### ISSUE THREAD

**Issue by mixmix** [ssb-ngi-pointer/ssb-bfe#19]
if something is already a buffer, then you might think it's already safely encoded.... so `bfe.encode(buf) === buf` might seem like a good idea.

however if that buffer was just some random buffer like `Buffer.from('cat')`, then it's not guarenteed to be in BFE format.
When you try and `decode` that buffer, you might get :
- a match of a type/ format (by chance!) and some junk string
- no match and an error.

**Comment by mixmix** [comment]
## proposal A

when a buffer is passed into `bfe.encode`, check `buf.slice(0,2)` is a registered type/format, and
IF it is known, then pass the buffer through
ELSE throw an error

---

pro: slightly safer
con: still subject to random stuff coming through on the offchance it's 2 bits are BFE type/format

**Comment by mixmix** [comment]
## proposal B

do not accept buffers
if a developer passes one in, throw

This forces the developer to decide if the buffer is encoded yet or not

**Comment by staltz** [comment]
Hmm, really well spotted. I think adding a new type format to the spec might be a proper solution, for "uncategorized bytes"

**Comment by arj03** [comment]
Yeah agree, cc @cryptix

**Comment by staltz** [comment]
Miscellaneous bytes :laughing:

**Comment by arj03** [comment]
rando bytes

**Comment by staltz** [comment]
In fact, I think some random CI errors for ssb-meta-feeds is coming precisely from this issue

**Comment by mixmix** [comment]
I'm still down for throwing
Why the hell would you want random bytes. My bytes will be typed!

**Comment by cryptix** [comment]
I feel it's still good to prefix raw bytes, if only to keep our "extended bencode" pattern consistent. Also [List of file signatures (aka magic bytes)](https://en.wikipedia.org/wiki/List_of_file_signatures) also doesn't list `0x0603`, so it would have to be a raw hash value to slip through and one could still argue that it's a code error to construct them like that.

re proposal B: how would you allow developers to pass in arbitrary bytes then? via a special function, i guess (while not being familiar with the JS module API). butt i also feel like it's more of a API then encoding question. Meaning: why not have both?
